
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURET = "USER_REGISTRATION_FAILURET";

export const FETCH_BUDGET_lIST_REQUEST = "FETCH_BUDGET_lIST_REQUEST";
export const FETCH_BUDGET_lIST_SUCCESS = "FETCH_BUDGET_lIST_SUCCESS";
export const FETCH_BUDGET_lIST_FAILURE = "FETCH_BUDGET_lIST_FAILURE";
export const SAVE_BUDGET_REQUEST = "SAVE_BUDGET_REQUEST";
export const SAVE_BUDGET_SUCCESS = "SAVE_BUDGET_SUCCESS";
export const SAVE_BUDGET_FAILURE = "SAVE_BUDGET_FAILURE";
export const DELETE_BUDGET_REQUEST = "DELETE_BUDGET_REQUEST";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_FAILURE = "DELETE_BUDGET_FAILURE";

export const FETCH_EXPENSE_lIST_REQUEST = "FETCH_EXPENSE_lIST_REQUEST";
export const FETCH_EXPENSE_lIST_SUCCESS = "FETCH_EXPENSE_lIST_SUCCESS";
export const FETCH_EXPENSE_lIST_FAILURE = "FETCH_EXPENSE_lIST_FAILURE";
export const SAVE_EXPENSE_REQUEST = "SAVE_EXPENSE_REQUEST";
export const SAVE_EXPENSE_SUCCESS = "SAVE_EXPENSE_SUCCESS";
export const SAVE_EXPENSE_FAILURE = "SAVE_EXPENSE_FAILURE";
export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";

export const FETCH_INCOME_lIST_REQUEST = "FETCH_INCOME_lIST_REQUEST";
export const FETCH_INCOME_lIST_SUCCESS = "FETCH_INCOME_lIST_SUCCESS";
export const FETCH_INCOME_lIST_FAILURE = "FETCH_INCOME_lIST_FAILURE";
export const SAVE_INCOME_REQUEST = "SAVE_INCOME_REQUEST";
export const SAVE_INCOME_SUCCESS = "SAVE_INCOME_SUCCESS";
export const SAVE_INCOME_FAILURE = "SAVE_INCOME_FAILURE";
export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAILURE = "DELETE_INCOME_FAILURE";


export const LOGOUT = "LOGOUT";


export const SET_MAIN_PAGE = "SET_MAIN_PAGE";
export const SET_SUB_PAGE = "SET_SUB_PAGE";

export const UI_INTRO_PAGE = "UI_INTRO_PAGE";
export const UI_LOGIN_PAGE = "UI_LOGIN_PAGE";
export const UI_REGISTRATION_PAGE = "UI_REGISTRATION_PAGE";
export const UI_BUDGET_PAGE = "UI_BUDGET_PAGE";
export const UI_EXPENSE_PAGE = "UI_EXPENSE_PAGE";
export const UI_INCOME_PAGE = "UI_INCOME_PAGE";
export const UI_DASHBOARD_PAGE = "UI_DASHBOARD_PAGE";
export const UI_REPORT_PAGE = "UI_REPORT_PAGE";


export const SUB_UI_ADD_FORM = "SUB_UI_ADD_FORM";
export const SUB_UI_EDIT_FORM = "SUB_UI_EDIT_FORM"


export const ALERT_TYPE_INFO = "ALERT_TYPE_INFO";
export const ALERT_TYPE_SUCCESS = "ALERT_TYPE_SUCCESS";
export const ALERT_TYPE_WARNNG = "ALERT_TYPE_WARNNG";
export const ALERT_TYPE_ERROR = "ALERT_TYPE_ERROR";


export const REPORT_TYPE_CATEGORY_WISE = "categoryWise";
export const REPORT_TYPE_MONTHLY_REPORT = "monthlyReport";


export const REPORT_TYPE_INCOME_VS_EXPENSE = "Income vs. Expense Report";
export const REPORT_TYPE_BUDGET_VS_ACTUAL = "Budget vs. Actual Report";
export const REPORT_TYPE_MONTHLY_EXPENSE = "Monthly Expense Report";
export const REPORT_TYPE_ANNUAL_FINANCIAL_SUMMARY = "Annual Financial Summary";
export const REPORT_TYPE_CATEGORY_WISE_EXPENSE = "Category-wise Expense Report";

export const REPORT_PERIOD_TYPE_MONTHLY = "Monthly";
export const REPORT_PERIOD_TYPE_QUARTERLY = "Quarterly";
export const REPORT_PERIOD_TYPE_YEARLY = "Yearly";